### ISSUE TITLE
[StarLite Mk V] Add entry to ssdt to tell the OS the keyboard is internal

### ISSUE THREAD

**Issue by thmichel** [StarLabsLtd/firmware#182]
I noticed that the setting "disable touchpad while typing" does not work on Fedora. Not sure about other distros. This is pretty annoying while typing longer texts.

Solution is to create a local override for libinput. To do so, create a file called "/etc/libinput/local-overrides.quirks" with following content:

[Serial Keyboards]
MatchVendor=0x27C6
MatchProduct=0x0111
MatchUdevType=keyboard
AttrKeyboardIntegration=internal

**Comment by Sean-StarLabs** [comment]
> I noticed that the setting "disable touchpad while typing" does not work on Fedora.

Which way? And what model?

**Comment by thmichel** [comment]
Ah, sorry. Starlite MK V. Amended the title. Without that quirk, the palm on the  palm on the touchpad moves the vorsor around while typing and sometimes initiates a mouse click.

**Comment by Sean-StarLabs** [comment]
Fixed with 39dfcc167040e8ee36cc760e584a350142bdc4c7

**Comment by aral** [comment]
Just wanted to mention that I’m running firmware 24.08 and the issue still exists on Fedora Silverblue.

**Comment by aral** [comment]
Hmm, I wonder if this is actually an issue with tap-to-click not getting disabled when the disable touchpad while typing setting is on in GNOME and/or the StarLite firmware.

I’ve just re-enabled the trackpad but turned off tap to click and I don’t seem to be seeing the problem (and the mouse cursor does disappear while typing, which is did before too).
